### ISSUE TITLE
C compiler error in lib/Starlink/AST.xs

### ISSUE THREAD

**Issue by awacha** [Starlink/perl-Starlink-AST#1]
Dear Developers,

while packaging Starlink::AST for the Arch Linux User repository (https://aur.archlinux.org/packages/perl-starlink-ast), we have run into a problem. Using the default compiler flags results in critical errors, aborting the build:

cc -Isrc -Iast -I/usr/lib/perl5/5.34/core_perl/CORE -DVERSION="3.01" -DXS_VERSION="3.01" -fPIC -Iextsrc -DHAVE_DECL_ISNAN=1 -DSIZEOF_LONG=8 -DSIZEOF_LONG_LONG=8 -DHAVE_INT64_T=1 -DHAVE_UINT64_T=1 -c -D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Wno-error=format-security -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -flto -o lib/Starlink/AST.o lib/Starlink/AST.c
lib/Starlink/AST.xs: In function ‘XS_Starlink__AST__Frame_new’:
lib/Starlink/AST.xs:592:3: error: format not a string literal and no format arguments [-Werror=format-security]
  592 |   ASTCALL(
      |   ^~~~~~~
lib/Starlink/AST.xs: In function ‘XS_Starlink__AST__FrameSet_new’:
lib/Starlink/AST.xs:628:3: error: format not a string literal and no format arguments [-Werror=format-security]
  628 |   ASTCALL(
      |   ^~~~~~~
( and many more of this below)

This might be a vulnerability in the code, but as I'm not a Perl programmer, I cannot decide. For the present, I have disabled the corresponding flag in the build script, so the code compiles without any modification.

Would it be possible to modify the code so as to make it compatible?

Thank you and kind regards,

Andras

**Comment by grahambell** [comment]
It should be possible to build with `-Werror=format-security` as of version 3.02 (including commit 7051b740bdb4e28d252e8dbf4aceff24d78a14d7), just released.

**Comment by awacha** [comment]
Dear @grahambell,
thank you for the fix! I have also updated the package in the Arch User Repository.
